
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.nrbyzvxafymfgqalgilp
spring.datasource.password=2ClB7GUwuMmtO4pr

spring.datasource.driver-class-name=org.postgresql.Driver

app.frontend-origin=*

server.port=10000